In [1]:
import numpy as np

In [26]:
#let's build up an array 
#from here and below i'll use semicolons only in order to not forget to use them in C++ code 

arr = np.array((1, 2, 3));
arr_ = np.array(((1, 1), (2, 2)));

print(arr);
print("\n");
print(arr_);

[1 2 3]


[[1 1]
 [2 2]]


In [18]:
#let's get the type of an array's elements 
print(arr.dtype); 
#other properties of array:
# shape -> 
print(arr.shape);
# nbytes -> 
print(arr.nbytes);

int64
(3,)
24


In [37]:
#let's fill arrays with some sort of data 

arr1 = np.arange(1, 10, 2); #from, to, step 
print(arr1);

arr2 = np.zeros(7); #num of elements 
print(arr2);

arr3 = np.ones(7); #num of elements 
print(arr3)

arr4 = np.linspace(0, 10, 10); #kind a great way to do an interpolation #from, to, num of elements 
print(arr4);

arr5 = np.logspace(0, 3, 5); #from, to, num of elements 
print(arr5);

[1 3 5 7 9]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [46]:
#operation via arrays (or operation with const and array)

arr1 = np.array((1, 1, 1));
arr2 = np.array((2, 2, 2));

#sum 
print(arr1 + arr2); #each a[i] + b[i] 
#substraction 
print(arr1 - arr2); #each a[i] - b[i] 
#multiplication 
print(arr1 * arr2); #each a[i] * b[i] 
#division
print(arr1 / arr2); #each a[i] / b[i] 

[3 3 3]
[-1 -1 -1]
[2 2 2]
[0.5 0.5 0.5]


In [55]:
#also it's possible to use function for each element of array

print(np.cos(arr1)); #each cos(a[i])
#other functions:
#sin
#log

#usage of true/false sentences 
print(arr1 > arr2);

[0.54030231 0.54030231 0.54030231]
[False False False]


In [58]:
#∀ 
print(np.all(arr1 > arr2));


#∃
print(np.any(arr1 > arr2));

False
False
