In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
import torch

### Tensor 
Main data unit in PyTorch is the **Tensor**. In our understanding, **Tensor** is just a set of vectors n $v_1, v_2 ... , v_{n-1}, v_n$
$$Ten = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, v_1 = [1, 2, 3], v_2 = [4, 5, 6]
$$

Types of Tensors in `PyTorch`:
| 32-bit floating point   | torch.float32 or torch.float    | torch.FloatTensor    | torch.cuda.FloatTensor    |
|-------------------------|---------------------------------|----------------------|---------------------------|
| 64-bit floating point   | torch.float64 or torch.double   | torch.DoubleTensor   | torch.cuda.DoubleTensor   |
| 16-bit floating point 1 | torch.float16 or torch.half     | torch.HalfTensor     | torch.cuda.HalfTensor     |
| 16-bit floating point 2 | torch.bfloat16                  | torch.BFloat16Tensor | torch.cuda.BFloat16Tensor |
| 32-bit complex          | torch.complex32 or torch.chalf  |                      |                           |
| 64-bit complex          | torch.complex64 or torch.cfloat |                      |                           |

To initiate a **tensor** or may use a call with `list` or with `integer value `of elements in **tensor** 

In [5]:
a = torch.FloatTensor([1, 2])

In [8]:
print(a.size())

torch.Size([2])


In [10]:
b = torch.FloatTensor([[3, 4, 5],
                    [1, 2, 3]])

In [11]:
print(b.size())

torch.Size([2, 3])


In [13]:
c = torch.BFloat16Tensor(10)

In [14]:
print(c.shape)

torch.Size([10])


In [3]:
d = torch.IntTensor(2, 3, 4)

In [4]:
print(d)
print(d.shape)

tensor([[[          0,           0,           0,           0],
         [          0,           0,        1681,           0],
         [-1140826912,       32592, -1140826912,       32592]],

        [[          0,           0,           0,           0],
         [ -496192668,   -94700947,    90439681,   -76762012],
         [  -61146003, -1251737599,     8697444,    90504538]]],
       dtype=torch.int32)
torch.Size([2, 3, 4])


As you may notice, .shape an .size() give the same results 

To make tensor full of zeroes (inplace solution)


In [5]:
d.zero_()

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

Random data distribution realizations

In [11]:
x = torch.randn((2, 3)) # Normal(0, 1) with size (2, 3)
x

tensor([[ 0.9162, -0.8831, -1.7545],
        [ 0.3536, -0.0140,  1.9930]])

In [23]:
x.random_(0, 10) #Discrete from [0, 10]

tensor([[2., 9., 3.],
        [7., 3., 8.]])

In [16]:
x.uniform_(0, 10) #Continiously from [0, 10]

tensor([[1.7870, 1.3596, 9.6161],
        [4.0172, 2.2870, 3.6685]])

In [26]:
x.normal_(mean = 5, std = 1) # Normal distribution with mean and sigma

tensor([[4.8060, 5.9577, 4.6449],
        [3.3300, 6.2051, 4.7885]])

In [25]:
x.bernoulli_(p = 0.5)

tensor([[0., 1., 0.],
        [0., 1., 1.]])

Reshape of tensor **torch.tensor.view() = np.reshape()**

In [32]:
x = torch.Tensor([1, 2, 3, 4])
x.view((2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [36]:
x.reshape(-1)

tensor([1., 2., 3., 4.])

Retyping the Tensors:

In [41]:
exmpl = torch.Tensor([1, 2, 3])
exmpl.type_as(torch.FloatTensor())

tensor([1., 2., 3.])

In [43]:
exmpl = torch.Tensor([[1, 2, 3], [4, 5, 6]])
exmpl.to(torch.float16)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

Arithmetics goes as in usuall python, but it's better to notice that it possbile to use `.add()`, `.sub()`, `.mul()`, `.div()` instead of boring +, -, *, \

To Transport the matrix use `Tensor.t()`

In [46]:
x = torch.IntTensor([[1, 2], [4, 3]])
print(x)
x.t()

tensor([[1, 2],
        [4, 3]], dtype=torch.int32)


tensor([[1, 4],
        [2, 3]], dtype=torch.int32)

To include data from numpy to torch

In [51]:
a = np.array([1, 2, 3, 5])
b = torch.from_numpy(a)
print(b)

tensor([1, 2, 3, 5])


To include data from pytorch to numpy

In [49]:
b.numpy()

array([1, 2, 3, 5])

### Firt Approach to Neurons

In [54]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])

In [57]:
def forward_pass(X, w):
    data_result = X @ w
    return torch.sigmoid(data_result)

In [58]:
forward_pass(X, w)

tensor([[1.0000],
        [0.9985],
        [0.0474]])

### CUDA Computations

In [59]:
!nvidia-smi

Wed Oct 26 22:34:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P3    13W /  N/A |      5MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')

In [4]:
x = torch.Tensor([1, 2, 3]).to(device)

In [5]:
!nvidia-smi

Wed Oct 26 22:56:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P3    14W /  N/A |    797MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------